src/article/dto/find-all-article.dto.ts

- 기존에 type을 Int 로 검사하던걸
- numberstring 으로 변경
- querystring은 문자열이라서, int로 검사가 불가능함

Fix: 게시글 검색시, query string validate 오류 수정

---

src/article/article.service.ts
src/article/entities/article.entity.ts
src/article/repositories/article.repository.ts
src/category/category.service.ts
src/category/entities/category.entity.ts
src/comment/comment.service.ts
src/comment/entities/comment.entity.ts
src/user/entities/user.entity.ts
src/user/repositories/user.repository.ts
src/user/user.service.ts

* 게시물, 댓글, 유저 SoftDelete 추가
* 카테고리에도 SoftDelete 를 추가하였습니다.
* @DeletedDateColumn 을 사용하면,
* typeorm 이 find할떄 자동으로 deleted_at의 여부에 따라서 걸러준다고 합니다.
* 심지어 createQueryBuilder에서 getOne 할떄도, 적용되는거 확인했습니다.
* 대신, raw query로 구현되어있는 부분은 query를 수정하였습니다.
[참고](https://wanago.io/2021/10/25/api-nestjs-soft-deletes-postgresql-typeorm)

Feat: soft delete 추가

---

src/article/article.service.ts
src/article/repositories/article.repository.ts
src/category/repositories/category.repository.ts
src/comment/comment.service.ts
src/comment/repositories/comment.repository.ts
src/user/repositories/user.repository.ts

* 댓글 가져올떄, 게시글이 지워져있는지 한번 확인하도록 수정하였습니다.
* existOrFail구현시, 문자열처리를 다시 수정하였습니다.
* 게시글의 존재 유무를 확인해야 댓글을 확실히 안가져올수있습니다.

Fix/지워진 게시글의 댓글에 접근가능한 오류 수정

---

src/comment/comment.controller.ts
src/comment/dto/create-comment-result.dto.ts

- 댓글 생성한 사람의 닉네임 추가
- 프론트에서 댓글 생성 직후 사용자의 닉네임이 필요하여 추가됨

Feat: 댓글 생성 api 결과값 변경

---

src/app.controller.ts
src/app.module.ts
src/ft-checkin/ft-checkin.controller.spec.ts
src/ft-checkin/ft-checkin.controller.ts
src/ft-checkin/ft-checkin.module.ts
src/ft-checkin/ft-checkin.service.spec.ts
src/ft-checkin/ft-checkin.service.ts

- apps에 있던 42 checkin service를 리팩토링 했습니다.
- 도저히 참을 수 없었기 때문 ... 🤣 
- 상수를 따로 뺐으나, 이 기능에서만 사용될 것 같아 한 파일 내에서 관리합니다.
- apps에 있던 것을 새로 모듈을 파서 관리하였습니다.

Refactor: 42 checkin service move from apps

---

src/database/ormconfig.ts

- typeorm에 timezone 을 추가했습니다.
- db에는 값이 잘 들어가지만,
- typeorm 에서 다시 값을 바꿔버리고 있어서 시간이 달랐습니다.
https://soo-sin.tistory.com/m/24

Fix: typeorm 에 timezone 설정

---

src/comment/comment.controller.ts
src/comment/dto/create-comment-result.dto.ts

- 지금당장은 join한 결과를 응답하고 있지 않기 때문에
- 임시방편으로 댓글 생성 결과 dto에 writer 를 넣는것으로 수정하였습니다
- 프론트에서 writer가 join된 결과에서 nickname을 찾아 출력하고있어서 수정했습니다.
- 사실 프론트에서도 본인 닉네임을 가지고있기 때문에 백엔드에서 안보내줘도 되지만,
- 생성dto 와 검색 결과 dto 를 일관성있게 하는게 좋을지는 고민해봐야할거같습니다.
- 추후에 프론트와 논의가 필요할거같습니다.

Fix: 댓글 생성 결과 dto 수정

---

src/database/ormconfig.ts

- typeorm log, dev 환경일때만 되도록 수정
- alpha, prod 같은 배포 환경에서는 쿼리 로그보다는 다른 로그를 더 많이 봐야하기 때문에 typeorm log가 안찍히도록 config 수정
- ormconfig의 loggin을 true로 하면 typeorm이 생성하여 실행하는 쿼리를 로깅 할 수 있다.

typeorm log, dev 환경일때만 되도록 수정

---

src/app.controller.ts
src/auth/auth.controller.ts
src/filters/all-exception.filter.ts
src/filters/constant.ts
src/filters/internal-server-error-exception.filter.ts
src/filters/typeorm-exception.filter.ts
src/main.ts
src/utils.ts

- 500에러 글로벌 필터 적용
- 해당 필터에서 slack으로 에러메시지 발송하도록 기능 추가
- 모든 에러를 처리하는 필터 추가, github callback api에서는 이 에러필터를 사용
- 기존에 db에러만 잡고 있었기 때문에 500 에러도 처리하고 슬랙으로 메시지 보낼수 있도록 수정
- github callback api에서 발생하는 500 에러 필터로 잡히지 않아 모든 에러를 처리하는 필터를 별도로 사용
close #69

500 error 글로벌 필터 적용, 에러 발생시 슬랙으로 메시지 발송

---

src/article/article.controller.ts

increaseViewCount가 article.writerId(작성자 id)와 UserId(글을 보고 있는 유저 id)가 다를 경우에만 실행되도록 변경하였습니다.
조회수를 올리기 위해 여러 번 들어가 조회수를 일부러 올리는 작성자(= 나)를 막기 위해 작성자가 아닌 경우에만 조회수가 올라가도록 수정하였습니다.  
원래 여기엔 뭘 써야 할까요...? 음... 이걸 고치기 위해 많은 도움을 주신 ycha님 샤라웃하겠습니다 ㅎㅎ

[FIX] 작성자가 글에 접속하면 조회수가 오르지 않도록 수정

---

Makefile

- sudo는 alpha에서만 붙이도록 수정
- make dev 실행 할때 sudo로 실행되면 dist가 root로 생성되어 삭제하기 귀찮은 문제가 있었음

make dev가 불편해서 개편, sudo 제거, yarn start:dev 추가

---

src/image/image.controller.ts

- image api에 누락된 Authroize 어노테이션 추가
- 실수로 `@ApiCookieAuth()` 빼먹은거 추가하였음
- 실제로는 쿠키를 사용하고 있는데 어노테이션을 빼먹어서 swagger에서 모든 사용자가 사용할 수 있다는 api로 인지될 가능성 있어서 수정함

Doc: image api cookie auth swagger 추가

---

test/e2e/user.e2e-spec.ts

- 내가 좋아요 누른 게시글 목록 response 변경에 따른 test code 수정
- response 형태가 reactionArticle[]에서 article[]로 수정되었기 때문

Test: 내가 좋아요 누른 게시글 목록 response 변경에 따른 test code 수정

---

src/ft-auth/ft-auth.controller.ts

- all filter 적용
- 이메일 전송 api에서 생기는 구글 로그인 에러를 잡기 위해 all filter 적용
- all filter는 nest에서 정의하지 않은 에러도 처리 할 수 있는 필터이기 때문에 외부 라이브러리나 api에서 생기는 에러를 잡기 위해 사용

!HOTFIX: 이메일 전송 api에서 나는 구글 에러를 잡기 위해 all filter 적용

---

docker-compose.yml

- docker-compose 파일 내부에 db healthcheck 수정
- 환경 변수를 지정을 제대로 안해줘서 healthcheck가 제대로 안되고 있었음

Fix: docker compose db 헬스체크 스크립트 오류 수정

---

src/utils.ts

- error hook, prod 일대만 알람이 가도록 변경
- 테스트, 로컬, 알파에서 나는 에러는 굳이 슬랙으로 받을 필요가 없기 때문

FIx: slack error hook, prod일때만 알람이 가도록 변경

---

config/sample.env.dev
src/main.ts

- origin 관리를 env로 하도록 변경
- env로 cors를 관리하면 phase에 따라 cors를 다르게 설정하기 편하기 때문에 지금과 같이 변경하였음
- 예를 들면 prod에서는 localhost 접근이 안되게 하는것

Feat: origin 관리를 env로 하도록 변경

---

.github/workflows/test.yml

- github action을 통한 test cli 추가
- 올라온 pr의 테스트 코드 실행 여부를 매번 확인하기 어려워서 추가
- github secret을 이용할때 GITHUB으로 시작하는 secret이 존재하면 등록되지 않아서 github 관련 env는 NEST_를 붙여서 등록하였음
- 실제 env로 사용할때는 workflow에서 제대로 들어가도록 지정했기 때문에 문제 없음

Feat: github action을 통한 test workflow 추가

---

src/ft-checkin/ft-checkin.service.ts

- ft-checkin 서비스의 상수 변경
- 오타로 인해 값이 없는걸로 나오고 있었음

Fix: ft-checkin 서초 필드 오타때문에 값이 0으로 나오는 문제 수정

---

src/article/repositories/article.repository.ts
src/comment/repositories/comment.repository.ts
src/database/seeder/user/data.ts
src/pagination/dto/pagination-request.dto.ts
src/reaction/repositories/reaction-article.repository.ts
src/utils.ts

페이지네이션에서 skip 속성을 가져오지 못해서 utils에서 따로 처리하도록 변경
IntersectionType 을 사용할떄, skip 속성을 가져오지 않아서, skip이 undefined 가 된다.
utils에 getPaginationSkip 함수를 하나 만들어서 사용하도록 변경했습니다.

Hotfix: pagination skip 오류 수정

---

test/e2e/user.e2e-spec.ts
test/e2e/utils/dummy.ts
test/e2e/utils/utils.ts

- 유저 테스트의 부족한 테스트 케이스를 추가했습니다
- 테스트 보강을 위해 변경했습니다
- /users/{id} [실패] GET - 없는 유저 id를 요청한 경우
- /users [성공] PUT - 닉네임 길이가 0인 경우
- /users [성공] PUT - 닉네임만 변경하는 경우
- /users [성공] PUT - 캐릭터만 변경하는 경우
- /users [성공] PUT - 중복된 닉네임인 경우
- /users [실패] PUT - 없는 캐릭터 번호
위 테스트 케이스를 추가했습니다.
몇몇 실패 케이스는 스웨거에 반영이 안 된 경우가 있어 추후에 반영하면 좋을 것 같아요
주석을 확인해주면 감사합니다

Feat: 유저 테스트 케이스 추가

---

.github/workflows/test.yml
package.json
src/intra-auth/intra-auth.controller.ts
src/main.ts
test/e2e/intra-auth.e2e-spec.ts
test/e2e/utils/utils.ts
yarn.lock

- intra-auth 이메일 인증, get api test 추가
- createTestApp 유틸 함수 추가
- test 코드에서 nest app을 생성하고 filter, pipe, cookierParser를 적용하는 코드가 반복되서 별도의 함수로 분리
- 이메일 인증 후 렌더링 되는 ejs를 로컬 ejs 파일을 읽어서 검증하는 방식
-  test 코드에서는 ejs를 html 파일로 변환하는 과정이 없기에 ejs 파일을 읽어서 그대로 비교하면 검증이 가능함

Feat: intra-auth 메일 인증 test 추가

---

test/e2e/article.e2e-spec.ts
test/e2e/utils/dummy.ts
test/e2e/utils/utils.ts
test/e2e/utils/validate-test.ts

기존에 복잡하던 validate 테스트를 함수 하나로 줄임
게시글에서 확인해야하는 케이스 확인
기존 jwt 함수를 보완한  jwt2 함수 추가됨 -> 추후에 이걸로 바꿨으면 좋겠어요
테스트 짜는 순서
1. 정상적인 시나리오대로 성공 케이스 작성
2. 권한 관련해서 실패 케이스 작성
3. 400을 제회의한 의도적인 예외처리 관련해서 실패 케이스 작성
4. dto 에서 날수있는 예외처리 관련해서 실패 케이스 작성
성공 케이스는 응답값 다 잘 있는지 확인할것
실패 케이스는 상태코드만 확인할것
/**
* test module 유틸로 빼기
* HttpStatus.INTERNAL_SERVER_ERROR 쓸것
* 더미 데이터 어떻게 할지 고민해볼것
* response dto 가 제대로 확인되고있는지 체크할것
* unauthenticated 에러가 잘 나오는지 확인할것
* :id 말고 {id} 쓸것
* join 되는 엔티티는 join 이 잘되어있는지 속성 잘 확인할것
* 필요한 더미 데이터 정의는 describe 안에서 할것
*/

Feat: 게시글 테스트 보강

---

test/e2e/category.e2e-spec.ts
test/e2e/utils/utils.ts

- category API 테스트 케이스를 추가 하였습니다.
- 디렉토리 변경을 위한 테스트코드가 필요했습니다.
- user와 category를 배열로 구성하였습니다.
- user더미는 0번이 admin, 1번이 cadet, 2번이 novice 입니다.
- 모든 테스트는 admin, cadet, novice로 나누어 진행하였습니다.
- 카테고리 종류를 가져오는 부분은 배열형태인지 확인 후 각 요소의 이름을 확인하였습니다.
-----------------------------------------------------
추가
- createTestApp util 합병하였습니다.
- users 객체로 변경하였습니다. (admin, cadet, novice)
- category 객체로 변경하였습니다. (자유게시판, 익명게시판, 유머게시판)
- jwt 객체로 변경하였습니다. (admin, cadet, novice)
- 파라미터 id값 beforeEach에서 재사용하였습니다.
-----------------------------------------------------------
- /categories [성공] POST - ADMIN이 카테고리 생성
- /categories [실패] POST - CADET이 카테고리 생성
- /categories [실패] POST - NOVICE가 카테고리 생성
- /categories [실패] POST - unauthorized
- /categories [성공] GET - ADMIN이 카테고리 종류 가져오기
- /categories [성공] GET - CADET이 카테고리 종류 …

Feat: 카테고리 테스트 케이스 추가

---

src/article/article.controller.ts
src/category/category.controller.ts
src/comment/comment.controller.ts
src/image/image.controller.ts
src/reaction/reaction.controller.ts

ApiOkResponse로 명세된 POST 응답들의 명세를 ApiCreatedResponse로 수정
#162 /intra-auth 뿐만아닌 post 요청에서 201 응답이 날아오는 부분에 관한 명세를 알맞게 수정
POST /intra-auth의 경우에는 상의 후 201로 명세를 표기 할 지 응답코드를 수정할지 결정

Fix: post response 응답코드 swagger 명세 수정

---

.eslintrc.js

eslint의 tsconfig파일을 찾는 경로를 workspace/ 에서 __dirname/ 으로 변경
vscode workspace를 42world-Backend로 열지 않으면 모든 ts파일에서 tsconfig 경로가 달라 인식을 못함
https://haeunyah.tistory.com/m/123

Chore: eslint configRootDir 절대경로로 지정

---

src/image/image.controller.ts
src/intra-auth/intra-auth.controller.ts
src/reaction/reaction.controller.ts
test/e2e/image.e2e-spec.ts
test/e2e/intra-auth.e2e-spec.ts
test/e2e/reaction.e2e-spec.ts

intra-auth
image
reation
에 대해서 POST 요청의 http응답코드가 201이였던걸 200으로 변경하였습니다.
POST이지만, 의미상 유의미한 리소스가 생성되는 api요청은 아니기때문에 200으로 하였습니다.
근데 조금 애매하긴하네요.. 그냥 201로 둬도 될거같기도하고... 
특히 reation은 버튼을 누를때마다 리액션이 생성되기도 하고 없어지기도 해서 그냥 PUT으로 바꾸는게 좀더 맞는거같다는 생각이 드네요

Feature: 응답 httpcode를 201에서 200으로 나오게 변경

---

Makefile
docker-compose.yml
src/app.module.ts
src/ft-checkin/ft-checkin.module.ts
src/ft-checkin/ft-checkin.service.ts

- ft-checkin에서 cache_manager 대신에 cache module을 사용하도록 수정
- redis 제거
- 레디스 인스턴스 서비스 운영비용상의 문제로 redis를 사용하지 않고 메모리에 캐싱하는 방식으로 수정
- ft-checkin의 테스트를 편하게 하기 위해 cache module 적용
- 직접 만든 module을 사용하면 mocking하기 쉬움

Refactor: Cache Module

---

yarn.lock

nextjs/cli version이 8.2.0에서 8.2.5로 bump되었습니다.
minimist 보안이슈를 해결하기 위한 업그레이드
관련 종속성 패키지들도 같이 bump 되었습니다.

Chore: bump nestjs/cli from 8.2.0 to 8.2.5

---

yarn.lock

cache-manager의 version이 3.6.0에서 3.6.1로 upgrade되었습니다
async의 보안성 이슈를 해결하기 위함
ejs에서 종속중인 jake에서 사용중인 0.9.2 버전에도 같은 이슈가 존재합니다
jake 레포에서도 관련 이슈가 언급되었고
https://github.com/jakejs/jake/issues/408
관련 사항이 반영되었으나 아직 릴리즈되지는 않았습니다
https://github.com/jakejs/jake/pull/411
새로운 jake버전이 릴리즈 되는대로 ejs버전도 upgrade 하도록 하겠습니다
*추가
ejs 레포에서도 관련 이슈가 언급되었고 영어가 약해 정확하진 않지만 아예 jake를 종속성에서 빼버리는 방향으로 진행하는거로 보이기도 하는군요...?
https://github.com/mde/ejs/issues/659

Chore: bump cache-manager from 3.6.0 to 3.6.1

---

apps/api/src/article/article.controller.ts
apps/api/src/article/article.service.ts
apps/api/src/comment/comment.controller.ts
apps/api/src/comment/comment.module.ts
apps/api/src/comment/comment.service.ts
apps/api/src/reaction/reaction.controller.ts
apps/api/src/reaction/reaction.module.ts
apps/api/src/reaction/reaction.service.ts
apps/api/test/e2e/article.e2e-spec.ts
apps/api/test/e2e/comment.e2e-spec.ts
apps/api/test/e2e/reaction.e2e-spec.ts

댓글 쓸 때 카테고리 권한을 확인합니다.
댓글들을 가져올때 카테고리 권한을 확인합니다.
게시글 좋아요를 누를때 카테고리 권한을 확인합니다.
댓글 좋아요 누를때 카테고리 권한을 확인합니다.
[comment.service.ts](https://github.com/42-world/42world-Backend/pull/182/files#diff-775b284d92b6ec217c18dbf2f06546b85a1bfc58254e6cf84669a0c256483933)
[reaction.service.ts](https://github.com/42-world/42world-Backend/pull/182/files#diff-6ef50315b22d42807724915b034fa002bf9f6551e57bb317ecad437c7b9ad9ce)
이 두 파일이 핵심적으로 변경되었습니다. 이 파일을 중점으로 리뷰 부탁드립니다.
* 아직 리액션 테스트는 구현하지 않았습니다.
* 카테고리에 너무 자주 접근하고있는데, 쿼리 최적화를 하거나, 캐싱을 써야할거같습니다..

Feature: 댓글/리액션 쓰기/읽기 할때 카테고리 권한에 따라 작동하도록 변경

---

apps/api/src/category/category.controller.ts
apps/api/test/e2e/category.e2e-spec.ts

category api 권한을 누구나 확인가능하도록 합니다.
테스트도 수정되었습니다.
세부 게시글 권한이 생겼기 때문에 카테고리 종류는 권한에 따라서 나눌필요가 없다고 판단했습니다.

Hofix: category 가져오기 api 권한을 novice 도 허용 했습니다.

---

libs/common/src/database/ormconfig.ts

- 모노레포로 하면서 이상하게 마이그레이션 파일이 컴파일 안됨
- import 하지 않은 파일은 컴파일 되지 않음
- 일단 급한대로 무의미하게 import 해서 강제로 컴파일 시킴
- 나중에 실제로는 import 하지 않아도 컴파일 되도록 수정필요함

Hotfix: 모노레포로 이동하니까 마이그레이션 컴파일 안되서 강제로 import 시킴

---

apps/api/test/e2e/category.e2e-spec.ts
apps/api/test/e2e/notification.e2e-spec.ts

const app을 위에서 선언된 app을 사용하도록 변경
타입추론 적용
위에서 선언된 app이 아래에서 다시 한번 선언되어 위의 app변수가 사용되지 않고 있었습니다

Refactor: category test duplicate declaration

---

.github/workflows/test.yml

README를 업데이트 할 때는 테스트가 돌아가지 않도록 했습니다
최근 README를 업데이트 할 때 테스트가 쓸데없이 돌아가는것 같아 수정했습니다
pr이름이 Docs: 로시작하는 pr은 무시하도록 할 수 있다면 더욱 좋을것 같습니다
특정 tag, branch는 인식할 수 있는것으로 보임

Chore: ignore README.md in testCI

---

yarn.lock

ejs의 버전이 3.1.6에서 3.1.7로 변경되었습니다
#175 와 같은 이유로 jake에서 사용중인 async의 보안이슈
https://github.com/jakejs/jake/pull/411
https://github.com/mde/ejs/issues/659
ejs, jake에서 전부 패치를 진행해 새로운 버전이 릴리즈 되었습니다

Chore: bump ejs from 3.1.6 to 3.1.7

---

apps/api/src/comment/comment.service.ts

알람 설정을 바꿈
본인이 쓴 글에 본인이 댓글을 달면 알람이 옴
- 글쓴이와 댓글 단 사람이 같지 않을 경우에만 알람을 생성

fix: 자기가 쓴 댓글 알람 방지

---

Makefile
apps/api/test/e2e/article.e2e-spec.ts
apps/api/test/e2e/category.e2e-spec.ts
apps/api/test/e2e/comment.e2e-spec.ts
apps/api/test/e2e/e2e-test.base.module.ts
apps/api/test/e2e/image.e2e-spec.ts
apps/api/test/e2e/intra-auth.e2e-spec.ts
apps/api/test/e2e/notification.e2e-spec.ts
apps/api/test/e2e/reaction.e2e-spec.ts
apps/api/test/e2e/user.e2e-spec.ts

- test base module 이름 변경
- base module에서 데이터베이스 부분 설정이 env 값을 사용하도록 수정
- e2e 테스트에서만 사용할것이기 때문에 좀 더 확실한 이름으로 변경
- test db에 붙는 값이 고정값으로 되어 있어서 env에 맞게 실행되도록 수정

Refactor: test base module

---

apps/api/src/ft-checkin/ft-checkin.service.ts
apps/api/test/e2e/best.e2e-spec.ts

fft-checkin을 batch에서 생성한 cache에 있는 값을 가져오도록 수정
ft-checkin.service file의 변경점이 conflict 해결과정중 사라진 부분을 복구

Hotfix: ft-checkin.service 복구

---

apps/api/src/article/article.service.ts
apps/api/src/article/repositories/article.repository.ts
apps/api/src/comment/comment.service.ts
apps/api/test/e2e/best.e2e-spec.ts

articleRepository의 count관련 함수삭제
articleService의 count관련 query 최적화
commentService의 count관련 query 최적화
commentService의 count관련 함수 async로 변경
1. 하나의 속성값을 바꿀때 객체를 전부 업데이트하여 모든 속성에 대한 업데이트가 이루어진다.
2. save함수는 값이 존재하지 않을경우 insert 존재할 경우 update를 하므로 값을 넣기전 select 구문으로 값이 존재유무를 확인하게 된다.
위의 2가지 이유로 query가 느려져 최적화 하였습니다
#149

Refactor: article, comment count query optimize

---

.dockerignore
Dockerfile

도커파일의 명령어를 수정했습니다
도커 파일 명령어는 하나씩 캐싱이 됩니다. 
위에서 아래로 체크하며 변경사항이 있을 시 해당 지점부터 아래 명령어를 전부 다시 처리합니다. 
기존에는 코드를 복사한 후에 npm install을 받았는데 이렇게 할 시 코드가 변경 될 때마다 라이브러리를 다시 다운 받습니다.
그래서 순서를 변경해서 npm install 후에 코드를 복사하도록 변경했습니다.
코드 변경시 코드 변경 지점부터 빌드를 하고 npm install도 다시 합니다.
코드를 변경하더라도 이전 내역은 캐시가 되어 넘어갑니다.

Feat: 도커 파일 변경

---

.eslintrc.js

eslint prettier의 endofline 설정 auto로 변경
Windows 에서는 줄바꿈으로 CRLF를 사용하여 오류가 발생해 Windows 개발환경에서도 개발 할 수 있도록 수정

Chore: Windows end of line lint

---

apps/api/src/auth/auth.constant.ts

- jwt 암호화 및 복호화에 사용하는 secret key를 env로 관리하도록
- 원래 env를 사용했어야했는데 누락되어 있었음

Fix: jwt 시크릿키 env 사용하지 않고 있던 문제 수정

---

libs/common/src/database/seeder/intra-auth/data.ts
libs/common/src/database/seeder/intra-auth/intra-auth-seeder.module.ts
libs/common/src/database/seeder/intra-auth/intra-auth-seeder.service.ts
libs/common/src/database/seeder/seeder.module.ts
libs/common/src/database/seeder/seeder.ts
libs/common/src/database/seeder/user/data.ts

- user seed 데이터를 권한별로 만들도록 수정
- novice, cadet, admin
- user 데이터에 맞게 intra-auth 데이터도 생성
- 여러 권한을 가진 계정이 개발할때 필요해서 변경하였음

Feat: seed 데이터 보강

---

apps/api/src/auth/auth.constant.ts
apps/api/src/auth/auth.module.ts
apps/api/src/auth/jwt.strategy.ts

- auth.module과 jwt.strategy에서 env를 process.env로 가져오는 방식을 사용하고 있던 부분 변경
- 서버 시작할때 jwt secret key가 비어있다고 서버가 안켜지는 문제 때문에 수정
- auth module이 로드 되는 시점에서는 process.env가 비어있어서 제대로 안되는 문제가 있음
- registerAsync로 env가 로드 된 이후의 시점에 사용 할 수 있도록 처리하였음

Fix: jwt secret key, env를 제대로 안읽어와서 생긴 문제 수정, 유저 토큰 파싱이 안되던 문제

---

apps/api/src/sentry.interceptor.ts

- sentry.interceptor에서 에러를 처리한 이후에 에러를 다시 전달하도록 수정하였음
- Fix: sentry interceptor에서 에러를 다시 전달 안해주는 문제가 있어서 수정하였음
- 참고자료: https://docs.nestjs.com/interceptors#exception-mapping

Fix: sentry intercetopr에서 에러를 다시 전달 안해주는 문제 수정

---

apps/api/src/auth/auth.controller.ts

로그아웃 컨트롤러 권한을 Public으로 변경하였습니다.
Public으로 되어있지 않아서 외부인은 사용하지 못하고 있었음

Fix: 42인증하지 않은 유저도 로그아웃 가능하도록 변경

---

apps/api/src/user/user.controller.ts

- user/me api를 novice도 사용 가능하도록 수정
- 프론트 리팩토링을 진행하던중 내정보를 가져오는 api는 하나로만 사용하는게 구조적으로 좋을거 같아서 수정함
- 내정보를 가져오는 api인데 권한이 없는것도 이상하기도 함
- 이제 외부 인원도 사용 할 수 있게 되면 어차피 42인증 없이도 본인 정보 볼수 있어야하기 때문에 수정함

Feat: 내정보 가져오기 api, novice도 가능하도록 수정

---

Makefile

- makefile에 clean-all의 삭제 경로 수정
- intra 경로가 생기면서 db 경로도 바뀌었는데 반영이 안되어 있었음

Fix: makefile, clean-all db 파일 삭제, 경로 수정

---

apps/api/src/article/article.service.ts
apps/api/src/category/category.service.ts
apps/api/src/comment/comment.controller.ts
apps/api/src/comment/comment.service.ts
apps/api/test/e2e/article.e2e-spec.ts
apps/api/test/e2e/comment.e2e-spec.ts

- 카테고리 관련 권한 에러 status를 406에서 403으로 변경
- 댓글 좋아요 0이하 관련 에러 status 406에서 400으로 변경
- 게시글 좋아요 0이하 관련 에러 status 403에서 400으로 변경
- http 표준의 의미와 맞지 않기 때문
아래의 자료를 참고
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406
https://www.whatap.io/ko/blog/40/

Fix: http error

---

.github/workflows/test.yml

actions-yarn 버전 3.0.0으로 변경
기존 2.3.0 버전에서 python2 가 지원되지 않아
test 가 정상적으로 작동하지 않았음

Fix: actions-yarn 버전 3.0.0으로 변경

---

.eslintrc.js
.prettierrc

- eslint rules에 'prettier/prettier' 옵션 제거
- 설정하면 prettierrc 파일을 읽지 않기 때문에 제거하였음
https://github.com/prettier/eslint-plugin-prettier#options

Fix: prettier 설정이 적용이 안되던 문제 수정

---

.github/workflows/codeql-analysis.yml

on.push trigger를 설정하고
paths-ignore에 텍스트파일들 무시하도록 추가
codeQL warning을 확인하려면 on.push를 trigger해야한다고 하더라구요

Fix: on.push trigger 설정

---

apps/admin/tsconfig.app.json
apps/batch/tsconfig.app.json

outDIr 속성 삭제함
build시 outDir 때문에 nest-cli 값과 충돌해서 제대로 빌드가 안되고있었음

Fix: tsconfig outDir 수정

---

.github/workflows/test.yml

yarn build를 수행해 test에서 확인하지 못하는 환경에서의 build 오류를 감지하도록함
이전에 test는 통과하였으나 실제 서버 run시 오류가 발생함
build뿐만 아니라 실행까지 해보면 좋을것 같은데 서버를 켰다가 정상작동을 확인하고 종료시키는 작업으로 동작시키는게 적절한 방법인지 의문입니다

Chore: test build 추가

---

apps/api/src/user/dto/response/base-user-response.dto.ts
apps/api/src/user/dto/response/user-profile-response.dto.ts
apps/api/src/user/dto/user-profile.mapper.ts
apps/api/src/user/user.controller.ts
apps/api/test/e2e/user.e2e-spec.ts
libs/entity/src/user/user.entity.ts

- user profile api에 intraId 추가
- user role 타입이 string으로 되어 있어서 enum으로 변경
- user.entity의 intraAuth를 LazyLoad 할 수 있도록 Promise 처리
- java spring 스타일로 dto 작성
- 마이페이지에서 intraId도 같이 보여줘야해서 추가하였음
- LazyLoad를 사용해보고 싶어서 적용해보았음
- dto가 api의 결과를 나타내는 역할을 할 수 있기 때문에 명시적으로 전부 작성하는 방법을 선택하였음
- 전부 명시적으로 작성하다보니 java spring 스타일처럼 dto가 작성되었음(getter, setter는 없지만)

Feat: user profile api에 intraId 추가

---

apps/api/src/auth/auth.controller.ts
libs/utils/src/utils.ts

- cookie 옵션, alpha, prod일때 다르게 설정 및 옵션 추가
- httpOnly 옵션 추가
- sameSite prod일때는 lax로 변경
- clearCookie를 할때 쿠키 옵션을 사용하도록 추가
- 쿠키를 자바스크립트로 조작할 수 없도록 httpOnly 옵션 적용
- alpha 일 경우 로컬에서 붙어서 작업할때 도메인이 다르다는 이유로 브라우저가 쿠키를 삭제하지 않아 sameSite=none 으로 설정

Fix: cookie 옵션, alpha, prod일때 다르게 설정 및 옵션 추가

---

Makefile
infra/docker-compose.yml

- makefile의 clean에 있는 오타 수정
- docker compose file의 db의 플랫폼을 따로 지정안해주면 m1에서 안돌아가는 문제 수정
- 추후 mysql8로 올리면 플랫폼 키워드 없어도 될거 같습니다

Fix: makefile docker compose

---

apps/api/src/main.ts

front 에서 amplify 배포시 cors 에러를 regex 로 해결하기 위해 env 하나 추가했습니다.

CORS origin 으로 regex 를 쓸수있도록 변경

---

apps/api/src/comment/repositories/comment.repository.ts
apps/api/src/reaction/repositories/reaction-article.repository.ts
apps/api/test/e2e/user.e2e-spec.ts

- commentRepository의 findAllByWriterId 함수 내부 comment와 article의 조인을 left에서 inner 로 변경
- reactionArticleRepository의 findAllArticleByUserId 함수 내부 reactionArticle과 article의 조인을 left에서 inner 로 변경
- LEFT JOIN의 경우 join되는 테이블의 값이 없다면 null로 채워지기 때문에 INNER JOIN으로 변경

Fix: my comments, my reaction article
