42-world/42world-Backend

src/ft-auth/ft-auth.service.ts, src/ft-auth/ft-auth.utils.ts
- 암호화 방식을 바꿨습니다.
- 원래는 수제로 만들어 썼었는데, 특수문자 때문에 일치하지 않는 경우가 가끔 발생
- 암호화 방식을 수제에서 crypto 라이브러리를 쓰는 방식으로 바꿨습니다.
=> Fix: encrypt way

src/article/article.controller.ts, src/comment/comment.module.ts, src/comment/comment.service.ts, src/comment/entities/comment.entity.ts, src/comment/repositories/comment.repository.ts
- 댓글이 없다고 에러가 아니므라 get 을 find로 변경
=> Feat: 댓글에 유저 join

src/app.controller.ts, src/app.module.ts, src/app.service.ts, src/article/article.controller.ts, src/article/repositories/article.repository.ts, src/ft-auth/ft-auth.service.ts, src/ft-auth/ft-auth.utils.ts, src/utils.ts
- 게시글 리스트 내려줄 때 순서를 최신순으로 했습니다.
- 클러스터 입장 최대 인원 추가
=> Fix: 게시글 리스트 순서 정렬 및 클러스터 입장 최대 인원 추가

docker-compose.yml
- docker compose depends_on 옵션이 제대로 안되어있어 수정
=> Fix: docker-compose 디펜던시 제대로 안되던 문제 수정

src/article/entities/article.entity.ts
article entity의 title을 nullalbe false로 변경
- nullable로 되면 안되는데 되어 있어 수정
=> Fix: article title nullable 변경

.gitignore, Makefile, docker-compose.yml, docker-compose_backup.yml, src/utils.ts
- env 파일 이름 변경
- prod로 배포하면 제대로 안되는 문제가 있어서 .env 변경
=> FIx: env 파일 이름 형식 변경

package.json, src/app.controller.ts, src/app.module.ts, src/config/logger.mjs, src/config/logger.ts, src/main.ts, yarn.lock
- 로그 라이브러리 winston을 추가했습니다
- 로그를 파일로 남기도록 설정했습니다
- error, info, exception별로 로그 파일이 남습니다
- morgan 로그도 winston으로 남기게 설정했습니다
- 기존에 로그 시스템이 존재하지 않았고, 콘솔로만 남는게 불편해서 일자별로 로그 파일을 생성하도록 변경했습니다
/logs 아래에 로그 파일이 있습니다
morgan과 로그가 함께 콘솔로 찍힌 모습입니다
파일에는 json형식으로 로그가 저장됩니다
=> Feat: winston 로그 추가

src/database/seeder/user/data.ts
- user seed에 githubUid, githubUsername 추가
- user entity 변경에 된거에 맞춰서 수정
=> Fix: user seed data, entity 변경에 맞춰서 수정

test/e2e/comment.e2e-spec.ts, test/e2e/utils/utils.ts
comment test 추가
이에 대한 e2e 테스트가 없었어서
권한에 따른 실패/성공 테스트를 각각 작성
삭제된 댓글을 또 삭제한 경우 404가 아니라 200이 나와서 일단 이 테스트 케이스는 주석 처리함
=> Feat : comment test e2e

src/notification/notification.service.ts, test/e2e/notification.e2e-spec.ts, test/e2e/utils/dummy.ts, test/e2e/utils/utils.ts
- notification 테스트 추가
- e2e 테스트 필요
- /notifications [GET] 성공
- /notifications/readall [PATCH] 성공
=> Feat: notification 테스트 추가

test/e2e/notification.e2e-spec.ts
* Unauthhrized 실패 케이스 추가
* /notifications [GET] 실패
* /notifications/readall [PATCH] 실패
=> Test: Unauthrized 실패 케이스 추가

apps/api/tsconfig.app.json, apps/scheduler/tsconfig.app.json
json의 불필요한 콤마 삭제
콤마가 존재하여 다음줄을 다음 항목으로 인식하는 에러가 발생 할 수 있음
+ **Commit**:  f7220dce48075f99ec4df05755beca1eb3a14c2c
+ **File**:    [apps/api/tsconfig.app.json](https://github.com/42-world/42world-Backend/blob/f7220dce48075f99ec4df05755beca1eb3a14c2c/apps/api/tsconfig.app.json)
+ **LineNum**: [5](https://github.com/42-world/42world-Backend/blob/f7220dce48075f99ec4df05755beca1eb3a14c2c/apps/api/tsconfig.app.json#L5)
https://jsonformatter.curiousconcept.com/#
해당 formatter사이트 이용
현재 단락구분을 스페이스2개에서 vscode 자동 설정에 따른 탭으로 변경하였는데 의견 부탁드립니다
=> Refactor: json format error

README.md
Codacy라는 정적 분석 도구를 추가하였습니다
https://app.codacy.com/gh/42-world/42world-Backend
앞으로의 클린코드를 위하여
=> Docs: add codacy badge

README.md
sikang이 추가되었습니다
열심히 하겠습니다
청사과가 좋아요
=> Docs: 기여한 사람 추가

apps/api/src/article/repositories/article.repository.ts, apps/api/test/e2e/article.e2e-spec.ts, apps/api/test/e2e/best.e2e-spec.ts, apps/api/test/e2e/category.e2e-spec.ts, apps/api/test/e2e/comment.e2e-spec.ts, apps/api/test/e2e/image.e2e-spec.ts, apps/api/test/e2e/intra-auth.e2e-spec.ts, apps/api/test/e2e/notification.e2e-spec.ts, apps/api/test/e2e/reaction.e2e-spec.ts, apps/api/test/e2e/user.e2e-spec.ts, apps/api/test/e2e/utils/dummy.ts
best article 선정기준이 2주내에 업로드된 글만 선정되도록 변경
best api test 추가
createDummyArticle 함수 추가 및 article-test, best-test에 적용
#146 인기글 알고리즘 도입전 미리 간단한 알고리즘 도입
자세한 사항은 기획자분들과 전체회의때 정해봐야함
createDummyArticle 함수를 통해 2명의 유저가 각각 업로드한 글, 익명게시판글, 2주가넘은글, 추천이 많은 글을 한번에 생성하여 필요한것을 사용하도록 함
=> Feature: best article

apps/api/src/user/dto/base-user.dto.ts, apps/api/test/e2e/best.e2e-spec.ts
캐릭터 번호를 10번까지 사용 할 수 있도록 수정, swagger 명세 또한 수정
프론트 요구사항
=> Feat: 캐릭터 번호 10번까지 사용가능

.dockerignore, Dockerfile, Makefile, apps/api/src/article/article.service.ts, apps/api/src/article/repositories/article.repository.ts, apps/api/src/comment/comment.service.ts, apps/api/src/ft-checkin/ft-checkin.service.ts, apps/api/src/user/dto/base-user.dto.ts, apps/api/test/e2e/best.e2e-spec.ts, libs/common/src/database/ormconfig.ts, package.json
- docker swarm 적용
- redis 복구
- 배포 방식을 바꿔야 할 필요성을 느낌
- esc를 사용하고 있으나 사용법에 대한 미숙지 및 비용 문제로 인해 좀 더 간단한 방식을 사용 할 예정
- 하나의 인스턴스 내부에 redis를 사용한다면 비용문제는 없을것으로 보여서 redis는 복구함
- docker swarm 을 이용하면 간단하게 도커 오케스트레이션을 할 수 있음
- 주요 장점으로는 container가 죽어도 다시 살아난다는것과 배포 정책을 제공하여 무중단 배포가 쉽게 된다
- 부가적인 내용은 [노션](https://www.notion.so/euimin/docker-swarm-d490490128824630b4d4175c74614040)에 정리하였습니다
=> Feat: docker swarm

Makefile, docker-stack-prod.yml
- docker stack prod의 image 변경
- docker prod를 위한 build 및 push 명령어 makefile에 추가
- docker image를 관리하는 곳을 docker hub로 변경하고 해당 레파지토리의 주소로 변경하였음
=> Fix: docker prod

.github/workflows/auto_author_assign.yml
- 깃허브 액션 추가
- pr 올릴 때 본인 assign을 자동으로 해주는 액션을 추가했습니다
=> Setting: 자동으로 assignee 할당해주는 액션 추가

apps/batch/src/ft-checkin/ft-checkin.service.ts, apps/batch/src/main.ts
* 기준에 8시~23시만 가져오던 값을 매시간마다 가져오도록 변경
* 앱 처음시작시 값을 가져오도록 변경
* 인스턴스에 설정된 시간이 8 ~ 23와 맞지 않아서 의도하지 않은 시간에 값을 가져오지 않은 문제가있음
* 앱 처음 시작하고 5분이내로 값을 가져오지 않아서 api 서버에서 값이 없다는 오류가 발생함
=> Fix: ft checkin cron 처리 로직 변경

apps/api/src/article/article.controller.ts, apps/api/src/article/article.service.ts, apps/api/src/article/dto/request/search-article-request.dto.ts, apps/api/src/article/repositories/article.repository.ts, apps/api/test/e2e/article.e2e-spec.ts
- cateogryId를 query string에 포함시켜 함수를 하나로 합쳤습니다.
- 이에 따른 test code를 수정하였습니다.
- 코드 재사용과 프론트에서 api 호출 시 편의성을 위해
- category Id를 params가 아닌 query로 받는 방식으로 변경하였습니다.
=> Refactor: article search

apps/api/src/main.ts
swagger 상단바 스타일이 바뀌었습니다.
변경전
변경후
=> chore: swagger 상단바 제거

libs/utils/src/utils.ts
slack 알람은 alpha서버도 받도록 변경하였습니다.
슬랙 #error-alert-alpha 채널에 참여해주세요!
=> Feat: slack 알람 alpha도 받도록 변경

apps/api/src/user/dto/response/base-user-response.dto.ts, apps/api/src/user/dto/response/user-profile-response.dto.ts, apps/api/src/user/dto/user-profile.mapper.ts
user 응답에 githubUsername 추가했습니다.
프론트 요청사항
=> Feat: user response에 githubUsername 추가함

apps/api/src/article/article.service.ts, apps/api/src/article/dto/request/update-article-request.dto.ts, apps/api/test/e2e/article.e2e-spec.ts
article update request dto 수정
article service 수정
article e2e test 수정
article update를 할 때 category를 변경 불가하도록 명세 변경
=> Fix: remove categoryId of article update request dto

apps/api/src/user/user.controller.ts
=> fix: profile api 제거

apps/api/src/intra-auth/dto/signin-intra-auth-request.dto.ts
가입시 intra 아이디 대문자로 입력해도 소문자로 적용
대문자도 소문자로 바꿔서 가입시키자
=> fix: intra 아이디 소문자 적용

Makefile, libs/utils/src/utils.spec.ts
- includeRole 테스트 코드, guest 추가된거 반영
- makefile에서 unit test도 실행하도록 수정
- guest 추가된 이후로 테스트가 깨지고 있었기 때문에
=> Fix: unit test

apps/api/src/notification/notification.service.ts, apps/api/test/e2e/notification.e2e-spec.ts
=> fix: 알림 정렬 수정
